//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorks.ConsoleApp.ProductService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductService.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProducts", ReplyAction="http://tempuri.org/IProductService/GetProductsResponse")]
        AdventureWorks.DTO.Models.BL.BasketProduct[] GetProducts(int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProducts", ReplyAction="http://tempuri.org/IProductService/GetProductsResponse")]
        System.Threading.Tasks.Task<AdventureWorks.DTO.Models.BL.BasketProduct[]> GetProductsAsync(int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetDetails", ReplyAction="http://tempuri.org/IProductService/GetDetailsResponse")]
        AdventureWorks.DTO.Models.BL.ProductDetailsDTO GetDetails(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetDetails", ReplyAction="http://tempuri.org/IProductService/GetDetailsResponse")]
        System.Threading.Tasks.Task<AdventureWorks.DTO.Models.BL.ProductDetailsDTO> GetDetailsAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetImage", ReplyAction="http://tempuri.org/IProductService/GetImageResponse")]
        byte[] GetImage(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetImage", ReplyAction="http://tempuri.org/IProductService/GetImageResponse")]
        System.Threading.Tasks.Task<byte[]> GetImageAsync(int productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : AdventureWorks.ConsoleApp.ProductService.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<AdventureWorks.ConsoleApp.ProductService.IProductService>, AdventureWorks.ConsoleApp.ProductService.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AdventureWorks.DTO.Models.BL.BasketProduct[] GetProducts(int pageIndex, int pageSize) {
            return base.Channel.GetProducts(pageIndex, pageSize);
        }
        
        public System.Threading.Tasks.Task<AdventureWorks.DTO.Models.BL.BasketProduct[]> GetProductsAsync(int pageIndex, int pageSize) {
            return base.Channel.GetProductsAsync(pageIndex, pageSize);
        }
        
        public AdventureWorks.DTO.Models.BL.ProductDetailsDTO GetDetails(int productId) {
            return base.Channel.GetDetails(productId);
        }
        
        public System.Threading.Tasks.Task<AdventureWorks.DTO.Models.BL.ProductDetailsDTO> GetDetailsAsync(int productId) {
            return base.Channel.GetDetailsAsync(productId);
        }
        
        public byte[] GetImage(int productId) {
            return base.Channel.GetImage(productId);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetImageAsync(int productId) {
            return base.Channel.GetImageAsync(productId);
        }
    }
}
